import test from 'node:test';import assert from 'node:assert/strict';
import {distribution} from '../fframes/distribution-data.mjs';import {distributionScene} from '../fframes/distributions.mjs';
const input=()=>({title:'Sample',source:'Fictional sample.',asOf:'2026-09-30',unit:'dollars',observations:[-2,-1,0,1,2,null],edges:[-2,0,2],mode:'count',threshold:{value:0,relation:'gte'},y:{max:4,ticks:[0,2,4],decimals:0}});
test('histogram endpoints, nulls and exact threshold equality are explicit',()=>{const x=input(),old=structuredClone(x),m=distribution(x);assert.deepEqual(m.bins.map(b=>b.count),[2,3]);assert.equal(m.n,5);assert.equal(m.missing,1);assert.deepEqual(m.threshold.members,[2,3,4]);assert.deepEqual(x,old);for(const [relation,count]of [['gte',3],['gt',2],['lte',3],['lt',2]])assert.equal(distribution({...x,threshold:{value:0,relation}}).threshold.count,count);});
test('unequal bins use density whose area integrates to one',()=>{const x=input();x.edges=[-2,-1,2];x.mode='density';x.y={max:1,ticks:[0,1],decimals:0};const m=distribution(x);assert.deepEqual(m.bins.map(b=>b.count),[1,4]);assert.ok(Math.abs(m.bins.reduce((s,b)=>s+b.height*b.width,0)-1)<1e-15);x.mode='count';assert.throws(()=>distribution(x),/equal-width/);});
test('invalid and misleading histogram contracts fail explicitly',()=>{for(const edit of [x=>x.observations=[null],x=>{x.observations=[0,1];delete x.observations[0];},x=>x.observations=[3],x=>x.observations=[NaN],x=>x.edges=[-2,0,0],x=>x.threshold.value=3,x=>x.threshold.relation='above',x=>x.y.max=2,x=>x.y.ticks=[0,1.5,4],x=>x.extra=true,x=>x.mode='bell',x=>x.asOf='2026-02-30']){const x=input();edit(x);assert.throws(()=>distribution(x));}});
test('native distribution geometry retains full bins and exact observation x positions across focus',()=>{for(const [width,height]of [[1920,1080],[1080,1920]]){const x=input(),a=distributionScene(x,{width,height,id:'histogram',reveal:true}),b=distributionScene(x,{width,height,id:'tail',focus:true});assert.deepEqual(a.geometry.bars.map(v=>v.box),b.geometry.bars.map(v=>v.box));assert.deepEqual(a.geometry.points.map(v=>v.point),b.geometry.points.map(v=>v.point));assert.equal(b.geometry.points.filter(v=>v.selected).length,3);assert.ok(Math.abs(b.geometry.threshold.x-width*.54)<1e-9);for(const v of a.geometry.bars)assert.ok(Math.abs(v.box[1]+v.box[3]-height*(height>width?.59:.62))<1e-9);}});

test('scene rejects collapsed bars and packs selected outlines without overlap',()=>{const x=input();x.y={max:1e308,ticks:[0,1e308],decimals:0};assert.throws(()=>distributionScene(x,{width:1080,height:1920,id:'tiny'}),/positive bars/);x.y={max:4,ticks:[0,2,4],decimals:0};x.observations=[-1,-1,0];x.threshold={value:-1,relation:'lte'};const p=distributionScene(x,{width:1080,height:1920,id:'packed',focus:true}).geometry.points;assert.ok(p[1].point[1]-p[0].point[1]>2*p[0].r*1.3+2);});
