// Package current source-bound prototypes after native and independent review.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(root,'../../..'),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p))),write=(p,d)=>fs.writeFileSync(path.join(root,p),JSON.stringify(d,null,2)+'\n');
const audit=read('audit.json'),runs=read('build/verification.json').sort((a,b)=>a.name.localeCompare(b.name)),checks=read('build/encoded-checks.json'),reviews=read('evidence/independent-review/artifact-checks.json');
for(const list of [runs,checks,reviews])if(list.length!==8||new Set(list.map(r=>r.name??r.project)).size!==8)throw Error('Eight unique final variants required');
if(audit.inputSha256!==hash(path.join(root,'inputs.json')))throw Error('Inputs changed');
const tests=fs.readFileSync(path.join(root,'build/node-tests.txt'),'utf8');if(!tests.includes('pass 188')||!tests.includes('fail 0')||!tests.includes('skipped 0'))throw Error('Full regression evidence missing');
if(read('evidence/critique.json').some(r=>r.summary.warnings))throw Error('Critique warning remains');
const review=fs.readFileSync(path.join(root,'REVIEW.md'),'utf8');if(!review.includes(audit.inputSha256))throw Error('Review needs input binding');
const model=read('evidence/independent-review/contract-review.json');if(model.sourceSha256!==hash(path.join(repo,'engine/lib/asset-anchors.mjs'))||model.passed!==501)throw Error('Independent model evidence stale');
const source=read('evidence/source-checks.json'),projection=read('evidence/projection-checks.json');if(source.status!=='pass'||projection.status!=='pass'||projection.scriptSha256!==hash(path.join(root,'check-projection.py')))throw Error('Source check failed or stale');
for(const [p,h]of Object.entries(source.sourceFiles))if(hash(path.join(repo,p))!==h)throw Error('Source binding changed');
for(const s of source.variants){const p=projection.variants.find(x=>x.name===s.name),h=hash(path.join(root,'anchors',s.name+'.json'));if(s.manifestSha256!==h||p?.manifestSha256!==h)throw Error('Manifest check stale');}
const variants=[];
for(const r of runs){
 const dir=path.join(root,'evidence',r.name),video=path.join(dir,'video.mp4'),sb=path.join(root,'specimens',r.name,'storyboard.json'),receipt=JSON.parse(fs.readFileSync(video+'.json')),job=JSON.parse(fs.readFileSync(path.join(dir,'native-job.json'))),probe=checks.find(p=>p.project===r.name),reviewed=reviews.find(p=>p.name===r.name);
 if(r.check.errors.length||r.check.warnings.length||r.qa.pops||!r.seek.equal)throw Error('Native diagnostic remains');
 if(receipt.hashes['storyboard.json']!==hash(sb)||probe.videoSha256!==hash(video)||probe.storyboardSha256!==hash(sb)||probe.checkerSha256!==hash(path.join(root,'check-encoded.py'))||probe.failures)throw Error('Encoded binding stale');
 if(!reviewed.inspected||reviewed.captures<10||reviewed.videoSha256!==hash(video)||reviewed.storyboardSha256!==hash(sb))throw Error('Independent visual review incomplete');
 if(job.frames!==840||job.fps!==30||job.beats[0].frames!==240||job.beats[1].frames!==600)throw Error('Hold timing changed');
 variants.push({name:r.name,pipelineId:r.pipelineId,videoSha256:hash(video),storyboardSha256:hash(sb),check:r.check,qa:r.qa,seekEqual:true});
}
for(const [from,to]of [['build/node-tests.txt','evidence/node-tests.txt'],['build/focused-checks.txt','evidence/focused-checks.txt'],['build/encoded-checks.json','evidence/encoded-checks.json']])fs.copyFileSync(path.join(root,from),path.join(root,to));
write('evidence/implementation.json',{version:1,inputSha256:audit.inputSha256,sourceFiles:['engine/lib/asset-anchors.mjs','scripts/blender/export_anchors.py','engine/cli.mjs','fframes/job.mjs','fframes/native/src/canvas.rs'].map(p=>({path:p,sha256:hash(path.join(repo,p))}))});
const totals=Object.fromEntries(['nativeMappingChecks','sampledFrames','ringChecks','leaderChecks','frontChecks','failures'].map(k=>[k,checks.reduce((s,r)=>s+r[k],0)]));
write('evidence/summary.json',{status:'prototype',continuousPlayback:'unverified',variants,tests:{pass:188,fail:0,skipped:0},encoded:totals,limits:['Static geometry range only; no moving tracking or occlusion assessment','Conservative mesh boxes exclude shadow, blur, transparency and glyph fitting','Qualitative original mechanisms, not measured quantities','Bounded encoded probes and phone-frame review, not continuous playback or final master acceptance','Square and 4:5 unreviewed']});
const cards=runs.map(r=>`<article><h2>${r.name.replaceAll('-',' ')}</h2><video controls playsinline preload="none" src="evidence/${r.name}/video.mp4"></video><p><a href="specimens/${r.name}/storyboard.json">Editable source</a> · <a href="evidence/${r.name}/phone.png">Phone sheet</a></p></article>`).join('\n');
fs.writeFileSync(path.join(root,'preview.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Anchor studies</title><style>body{margin:0;background:#fafafa;color:#24272c;font:17px/1.5 system-ui}main{max-width:1200px;margin:auto;padding:40px}h1{font-size:42px}h2{font-size:19px}a{color:#344f9c}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:30px}article{padding:20px;border:1px solid #ddd}video{width:100%;height:430px;object-fit:contain;background:#eee}</style><main><h1>Anchor studies</h1><p>Native labels registered to original prepared Blender geometry. Four qualitative cases in landscape and vertical. <strong>Prototype:</strong> static attachment only; visibility, moving tracking and continuous playback acceptance remain open.</p><p><a href="README.md">Use and limits</a> · <a href="REVIEW.md">Independent review</a> · <a href="kit.json">File identities</a></p><div class="grid">${cards}</div></main><script>document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(o=>{if(o!==v)o.pause()})))</script></html>\n`);
function walk(dir,rel=''){return fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(e=>{if(['build','__pycache__','kit.json'].includes(e.name))return[];const f=path.join(dir,e.name),p=path.posix.join(rel,e.name);return e.isDirectory()?walk(f,p):[{path:p,bytes:fs.statSync(f).size,sha256:hash(f)}];});}
write('kit.json',{schemaVersion:1,id:'anchor-studies',version:'0.1.0',kind:'story-kit',title:'Anchor studies',status:'prototype',inventoryIds:['T03'],purpose:'Attach editable native labels to source-bound static prepared-asset points and reserved copy zones.',tags:{purpose:['annotate','explain-mechanism'],appearance:['paper','porcelain','glass'],movement:['mechanism-action','static-attachment','reading-hold'],format:['landscape','vertical'],subject:['access','levels','routes','bottlenecks']},includes:{source:'inputs.json',calculations:'audit.json',composition:'build.mjs',preview:'preview.html',specimens:runs.map(r=>`specimens/${r.name}/storyboard.json`)},requires:{replay:['ClearFrame native compositor','bundled fonts'],preparation:['Node.js','Blender','FFmpeg','Python 3','Original physical-mechanisms prepared scenes and receipts']},editable:{native:['copy','label placement','timing','leader','ring'],fixedClip:['Prepared mechanism pixels; regenerate geometry exports and review after source edits']},evidence:{summary:'evidence/summary.json',review:'REVIEW.md',encoded:'evidence/encoded-checks.json',implementation:'evidence/implementation.json',continuousPlayback:'unverified'},provenance:{references:'README.md',inputSha256:audit.inputSha256,modelVersion:1},license:'MIT for original files; bundled fonts retain OFL notices.',files:walk(root)});
console.log(JSON.stringify({variants:8,files:read('kit.json').files.length,encoded:totals}));
