// SPDX-License-Identifier: MIT
// Tabler icon geometry: Copyright (c) 2020-2026 Paweł Kuna.
// Generated by native/tools/generate-icons.py. Do not edit path data by hand.
// Source: github.com/tabler/tabler-icons @ 74929e50416e2b7c0abb8368cdc74bdcb2560ab6
// Full license and per-file source/SHA256: fframes/assets/icons/tabler/{LICENSE,manifest.json}.
use fframes::Svgr;

fn paths(name: &str) -> Option<&'static [&'static str]> {
    match name {
        "arrow-right" => Some(&[
            "M5 12l14 0",
            "M13 18l6 -6",
            "M13 6l6 6",
        ]),
        "book-open" => Some(&[
            "M3 19a9 9 0 0 1 9 0a9 9 0 0 1 9 0",
            "M3 6a9 9 0 0 1 9 0a9 9 0 0 1 9 0",
            "M3 6l0 13",
            "M12 6l0 13",
            "M21 6l0 13",
        ]),
        "brush" => Some(&[
            "M3 21v-4a4 4 0 1 1 4 4h-4",
            "M21 3a16 16 0 0 0 -12.8 10.2",
            "M21 3a16 16 0 0 1 -10.2 12.8",
            "M10.6 9a9 9 0 0 1 4.4 4.4",
        ]),
        "camera" => Some(&[
            "M5 7h1a2 2 0 0 0 2 -2a1 1 0 0 1 1 -1h6a1 1 0 0 1 1 1a2 2 0 0 0 2 2h1a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-9a2 2 0 0 1 2 -2",
            "M9 13a3 3 0 1 0 6 0a3 3 0 0 0 -6 0",
        ]),
        "check" => Some(&[
            "M5 12l5 5l10 -10",
        ]),
        "chef-hat" => Some(&[
            "M12 3c1.918 0 3.52 1.35 3.91 3.151a4 4 0 0 1 2.09 7.723l0 7.126h-12v-7.126a4 4 0 1 1 2.092 -7.723a4 4 0 0 1 3.908 -3.151",
            "M6.161 17.009l11.839 -.009",
        ]),
        "cloud-rain" => Some(&[
            "M7 18a4.6 4.4 0 0 1 0 -9a5 4.5 0 0 1 11 2h1a3.5 3.5 0 0 1 0 7",
            "M11 13v2m0 3v2m4 -5v2m0 3v2",
        ]),
        "compass" => Some(&[
            "M8 16l2 -6l6 -2l-2 6l-6 2",
            "M3 12a9 9 0 1 0 18 0a9 9 0 1 0 -18 0",
            "M12 3l0 2",
            "M12 19l0 2",
            "M3 12l2 0",
            "M19 12l2 0",
        ]),
        "droplet" => Some(&[
            "M7.502 19.423c2.602 2.105 6.395 2.105 8.996 0c2.602 -2.105 3.262 -5.708 1.566 -8.546l-4.89 -7.26c-.42 -.625 -1.287 -.803 -1.936 -.397a1.376 1.376 0 0 0 -.41 .397l-4.893 7.26c-1.695 2.838 -1.035 6.441 1.567 8.546",
        ]),
        "heart" => Some(&[
            "M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572",
        ]),
        "languages" => Some(&[
            "M9 6.371c0 4.418 -2.239 6.629 -5 6.629",
            "M4 6.371h7",
            "M5 9c0 2.144 2.252 3.908 6 4",
            "M12 20l4 -9l4 9",
            "M19.1 18h-6.2",
            "M6.694 3l.793 .582",
        ]),
        "leaf" => Some(&[
            "M5 21c.5 -4.5 2.5 -8 7 -10",
            "M9 18c6.218 0 10.5 -3.288 11 -12v-2h-4.014c-9 0 -11.986 4 -12 9c0 1 0 3 2 5h3l.014 0",
        ]),
        "lightbulb" => Some(&[
            "M3 12h1m8 -9v1m8 8h1m-15.4 -6.4l.7 .7m12.1 -.7l-.7 .7",
            "M9 16a5 5 0 1 1 6 0a3.5 3.5 0 0 0 -1 3a2 2 0 0 1 -4 0a3.5 3.5 0 0 0 -1 -3",
            "M9.7 17l4.6 0",
        ]),
        "map-pin" => Some(&[
            "M9 11a3 3 0 1 0 6 0a3 3 0 0 0 -6 0",
            "M17.657 16.657l-4.243 4.243a2 2 0 0 1 -2.827 0l-4.244 -4.243a8 8 0 1 1 11.314 0",
        ]),
        "microscope" => Some(&[
            "M5 21h14",
            "M6 18h2",
            "M7 18v3",
            "M9 11l3 3l6 -6l-3 -3l-6 6",
            "M10.5 12.5l-1.5 1.5",
            "M17 3l3 3",
            "M12 21a6 6 0 0 0 3.715 -10.712",
        ]),
        "music" => Some(&[
            "M3 17a3 3 0 1 0 6 0a3 3 0 0 0 -6 0",
            "M13 17a3 3 0 1 0 6 0a3 3 0 0 0 -6 0",
            "M9 17v-13h10v13",
            "M9 8h10",
        ]),
        "palette" => Some(&[
            "M12 21a9 9 0 0 1 0 -18c4.97 0 9 3.582 9 8c0 1.06 -.474 2.078 -1.318 2.828c-.844 .75 -1.989 1.172 -3.182 1.172h-2.5a2 2 0 0 0 -1 3.75a1.3 1.3 0 0 1 -1 2.25",
            "M7.5 10.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0",
            "M11.5 7.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0",
            "M15.5 10.5a1 1 0 1 0 2 0a1 1 0 1 0 -2 0",
        ]),
        "pencil" => Some(&[
            "M4 20h4l10.5 -10.5a2.828 2.828 0 1 0 -4 -4l-10.5 10.5v4",
            "M13.5 6.5l4 4",
        ]),
        "plane" => Some(&[
            "M16 10h4a2 2 0 0 1 0 4h-4l-4 7h-3l2 -7h-4l-2 2h-3l2 -4l-2 -4h3l2 2h4l-2 -7h3l4 7",
        ]),
        "sprout" => Some(&[
            "M12 10a6 6 0 0 0 -6 -6h-3v2a6 6 0 0 0 6 6h3",
            "M12 14a6 6 0 0 1 6 -6h3v1a6 6 0 0 1 -6 6h-3",
            "M12 20l0 -10",
        ]),
        "sun" => Some(&[
            "M8 12a4 4 0 1 0 8 0a4 4 0 1 0 -8 0",
            "M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7",
        ]),
        "timer" => Some(&[
            "M5 13a7 7 0 1 0 14 0a7 7 0 0 0 -14 0",
            "M14.5 10.5l-2.5 2.5",
            "M17 8l1 -1",
            "M14 3h-4",
        ]),
        "utensils" => Some(&[
            "M19 3v12h-5c-.023 -3.681 .184 -7.406 5 -12m0 12v6h-1v-3m-10 -14v17m-3 -17v3a3 3 0 1 0 6 0v-3",
        ]),
        "wind" => Some(&[
            "M5 8h8.5a2.5 2.5 0 1 0 -2.34 -3.24",
            "M3 12h15.5a2.5 2.5 0 1 1 -2.34 3.24",
            "M4 16h5.5a2.5 2.5 0 1 1 -2.34 3.24",
        ]),
        _ => None,
    }
}

pub(crate) fn supported(name: &str) -> bool { paths(name).is_some() }

/// Only an enumerated, locally pinned icon is allowed; props never supply SVG.
pub(crate) fn render<'a>(name: &str, x: f32, y: f32, size: f32, color: &str) -> Svgr<'a> {
    let geometry = paths(name).unwrap_or_else(|| panic!("unsupported native icon {name}"));
    let shapes: Vec<_> = geometry.iter().map(|path| fframes::svgr!(<path d={*path} />)).collect();
    fframes::svgr!(<g transform={format!("translate({x} {y}) scale({})", size / 24.0)}
        fill="none" stroke={color.to_owned()} stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        {shapes}
    </g>)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn only_named_trusted_icons_are_accepted() {
        assert!(supported("leaf"));
        assert!(supported("book-open"));
        assert!(!supported("../leaf.svg"));
        assert!(!supported("<svg><script>bad</script></svg>"));
    }
    #[test]
    fn pinned_geometry_survives_typed_svg_with_authored_color() {
        let icon = render("leaf", 20.0, 40.0, 72.0, "#123456");
        let svg = fframes::svgr!(<svg width="120" height="140" viewBox="0 0 120 140">{icon}</svg>);
        let tree = svg.into_svg_tree(&Default::default(), &mut fframes::usvgr::Cache::new_with_text_cache(1), &Default::default()).unwrap();
        let serialized = tree.to_string(&Default::default());
        assert!(serialized.contains("<path"));
        assert!(serialized.contains("#123456"));
        assert!(!serialized.contains("<image"));
    }
}
