//! Native ClearFrame starter. Content/timing come from a frozen job, not the network.
//! These two layouts are a starting point, not ports of the JS block library.
use fframes::{AudioMap, Duration, FFramesContext, Frame, Scene, Scenes, Svgr, Video};
use serde::Deserialize;

mod settings; // Generated by prepare; only canvas/fps changes require editing this file.
pub use settings::{FPS, HEIGHT, WIDTH};

#[derive(Debug, Deserialize)]
pub struct Row {
    pub label: String,
    pub value: f32,
}

#[derive(Debug, Deserialize)]
pub struct Beat {
    pub id: String,
    pub frames: usize,
    pub layout: String,
    pub headline: String,
    pub support: String,
    pub source: String,
    pub cue_seconds: f32,
    pub rows: Vec<Row>,
    pub max: f32,
}

#[derive(Debug, Deserialize)]
pub struct Film {
    pub width: usize,
    pub height: usize,
    pub fps: usize,
    pub frames: usize,
    pub beats: Vec<Beat>,
}

impl Film {
    pub fn read(file: &str) -> Result<Self, Box<dyn std::error::Error>> {
        let film: Self = serde_json::from_slice(&std::fs::read(file)?)?;
        if (film.width, film.height, film.fps) != (WIDTH, HEIGHT, FPS)
            || film.frames != film.beats.iter().map(|b| b.frames).sum::<usize>()
            || film.beats.is_empty()
        {
            return Err("job canvas/timing differs from this binary; prepare and rebuild".into());
        }
        for b in &film.beats {
            if b.frames == 0 || !matches!(b.layout.as_str(), "statement" | "bars")
                || !b.cue_seconds.is_finite() || b.cue_seconds < 0.0
                || !b.max.is_finite() || b.max <= 0.0
                || b.rows.iter().any(|r| !r.value.is_finite() || r.value < 0.0 || r.value > b.max)
            {
                return Err(format!("invalid native scene: {}", b.id).into());
            }
        }
        Ok(film)
    }
}

// Monotonic, seek-independent motion. No mutable playhead or wall clock.
fn ease_out(t: f32) -> f32 {
    1.0 - (1.0 - t.clamp(0.0, 1.0)).powi(3)
}

impl Scene for Beat {
    fn duration(&self) -> Duration<'_> { Duration::Frames(self.frames) }

    fn render_frame<'a>(&'a self, frame: Frame, _ctx: &FFramesContext<'a, '_>) -> Svgr<'a> {
        let t = frame.seconds();
        let p = ease_out((t - self.cue_seconds) / 0.6);
        let bars: Vec<Svgr> = self.rows.iter().enumerate().map(|(i, row)| {
            let y = 450.0 + i as f32 * 120.0;
            let grow = ease_out((t - self.cue_seconds - i as f32 * 0.1) / 1.2);
            let width = 1000.0 * row.value / self.max * grow;
            fframes::svgr!(<g>
                <text x="180" y={y + 36.0} font-family="Inter" font-weight="400" font-size="36" fill="#222831">{row.label.as_str()}</text>
                <rect x="530" y={y} width={width.max(0.01)} height="48" fill="#315cce" />
                <text x="1590" y={y + 36.0} font-family="Inter" font-weight="400" font-size="36" fill="#222831">{format!("{} h", row.value)}</text>
            </g>)
        }).collect();
        fframes::svgr!(<g>
            <text x="180" y="180" font-family="Inter" font-weight="400" font-size="30" fill="#505966">"RENDERER COMPARISON"</text>
            <g opacity={p} transform={format!("translate(0 {})", 20.0 * (1.0 - p))}>
                <text x="180" y="330" font-family="Inter" font-weight="600" font-size="76" fill="#222831">{self.headline.as_str()}</text>
                <text x="180" y="890" font-family="Inter" font-weight="400" font-size="38" fill="#505966">{self.support.as_str()}</text>
            </g>
            {bars}
            <text x="180" y="978" font-family="Inter" font-weight="400" font-size="28" fill="#505966">{self.source.as_str()}</text>
        </g>)
    }
}

impl Video for Film {
    const WIDTH: usize = WIDTH;
    const HEIGHT: usize = HEIGHT;
    const FPS: usize = FPS;
    fn duration(&self) -> Duration<'_> { Duration::Auto }
    fn audio(&self) -> AudioMap<'_> { AudioMap::none() } // Shared WAV is muxed by the adapter.
    fn define_scenes(&self) -> Scenes<'_> {
        Scenes::from(self.beats.iter().map(|b| b as &dyn Scene).collect::<Vec<_>>())
    }
    fn render_frame<'a>(&'a self, frame: Frame, ctx: &FFramesContext<'a, '_>) -> Svgr<'a> {
        fframes::svgr!(<svg xmlns="http://www.w3.org/2000/svg" width={WIDTH} height={HEIGHT} viewBox="0 0 1920 1080">
            <rect width="1920" height="1080" fill="#f5f3ed" />
            {ctx.render_scenes(&frame)}
        </svg>)
    }
}
