// Freeze current source, prepared media, native specimens and independent review.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(root,'../../..'),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p))),write=(p,d)=>fs.writeFileSync(path.join(root,p),JSON.stringify(d,null,2)+'\n');
const runs=read('build/verification.json').sort((a,b)=>a.name.localeCompare(b.name)),holds=read('build/encoded-holds.json'),registration=read('build/registration.json'),binding=read('bindings.json'),sourceReviews=read('evidence/independent-review/source-artifacts.json'),nativeReviews=read('evidence/independent-review/artifact-checks.json');
for(const rows of [runs,holds,registration,nativeReviews])if(rows.length!==8||new Set(rows.map(r=>r.name)).size!==8)throw Error('Eight unique native variants required');
if(hash(path.join(root,'inputs.json'))!==binding.inputSha256)throw Error('Inputs changed');
const tests=fs.readFileSync(path.join(root,'build/node-tests.txt'),'utf8');if(!tests.includes('pass 207')||!tests.includes('fail 0')||!tests.includes('skipped 0'))throw Error('Full tests missing');
if(read('evidence/critique.json').some(r=>r.summary.warnings))throw Error('Critique warning remains');
const model=read('evidence/independent-review/model-check.json');if(model.status!=='pass'||model.assertions<1308504||model.negativeCases<53||model.version1ExactSampleComparisons<2412||model.sourceSha256!==hash(path.join(repo,'scripts/blender/camera_rig.py')))throw Error('Independent camera model evidence incomplete or stale');
const review=fs.readFileSync(path.join(root,'REVIEW.md'),'utf8');if(!review.includes(binding.inputSha256))throw Error('Review needs input binding');
for(const[p,h]of Object.entries(read('evidence/independent-review/source-bindings.json')))if(hash(path.join(repo,p))!==h)throw Error('Review source stale '+p);
const mediaNames=[...new Set(binding.bindings.map(b=>b.mediaName))];if(mediaNames.length!==4||sourceReviews.length!==4)throw Error('Four prepared media reviews required');
for(const name of mediaNames){
 const dir=path.join(root,'media',name),receipt=read(`media/${name}/receipt.json`),geometry=read(`evidence/${name}/camera.json`),replay=read(`evidence/${name}/verification.json`),checked=sourceReviews.find(r=>r.name===name);
 if(!checked?.inspected||checked.sourceCaptures<8||checked.duration!==8||checked.frames!==192||checked.fps!==24||receipt.status!=='ready-for-review'||geometry.status!=='pass'||geometry.framesChecked!==193||!geometry.seekEqual||replay.status!=='passed-mechanical-checks')throw Error('Prepared review incomplete '+name);
 if(checked.sourceClipSha256!==hash(path.join(dir,'clip.mp4'))||checked.sceneSha256!==hash(path.join(dir,'scene.blend'))||checked.sourceReceiptSha256!==hash(path.join(dir,'receipt.json'))||checked.cameraReportSha256!==hash(path.join(root,'evidence',name,'camera.json'))||checked.replayReportSha256!==hash(path.join(root,'evidence',name,'verification.json')))throw Error('Prepared binding stale '+name);
 for(const[f,v]of Object.entries(receipt.outputs))if(hash(path.join(dir,f))!==v.sha256)throw Error('Prepared output stale '+f);
 for(const[f,h]of Object.entries(receipt.sourceHashes))if(hash(path.join(repo,f))!==h||hash(path.join(dir,'source',path.basename(f)))!==h)throw Error('Prepared source stale '+f);
 if(geometry.sceneSha256!==hash(path.join(dir,'scene.blend'))||geometry.receiptSha256!==hash(path.join(dir,'receipt.json')))throw Error('Geometry stale '+name);
}
const variants=[];
for(const r of runs){
 const dir=path.join(root,'evidence',r.name),sb=path.join(root,'specimens',r.name,'storyboard.json'),video=path.join(dir,'video.mp4'),receipt=JSON.parse(fs.readFileSync(video+'.json')),job=JSON.parse(fs.readFileSync(path.join(dir,'native-job.json'))),b=binding.bindings.find(b=>b.name===r.name),h=holds.find(h=>h.name===r.name),p=registration.find(p=>p.name===r.name),v=nativeReviews.find(v=>v.name===r.name);
 if(r.check.errors.length||r.check.warnings.length||r.qa.pops||!r.seek.equal||!h.passed||!p.passed)throw Error('Native diagnostic remains '+r.name);
 if(job.frames!==540||job.fps!==30||job.beats.map(x=>x.frames).join(',')!=='240,300'||receipt.frames!==540||receipt.fps!==30)throw Error('Native duration changed '+r.name);
 const sh=hash(sb),vh=hash(video);if([b.storyboardSha256,h.storyboardSha256,p.storyboardSha256,v.storyboardSha256,receipt.hashes['storyboard.json']].some(x=>x!==sh)||[h.videoSha256,p.videoSha256,v.videoSha256].some(x=>x!==vh))throw Error('Native binding stale '+r.name);
 if(!v.inspected||v.captures<11||v.duration!==18||v.nativeJobSha256!==hash(path.join(dir,'native-job.json'))||v.registrationReportSha256!==hash(path.join(root,'build/registration.json')))throw Error('Native review incomplete '+r.name);
 if(p.checkerSha256!==hash(path.join(root,'check-registration.py'))||h.geometrySha256!==hash(path.join(root,'evidence',b.mediaName,'camera.json')))throw Error('Encoded checker stale '+r.name);
 variants.push({name:r.name,pipelineId:r.pipelineId,videoSha256:vh,storyboardSha256:sh,check:r.check,qa:r.qa,seekEqual:true});
}
for(const[from,to]of [['build/node-tests.txt','evidence/node-tests.txt'],['build/focused-checks.txt','evidence/focused-checks.txt'],['build/encoded-holds.json','evidence/encoded-holds.json'],['build/registration.json','evidence/registration.json']])fs.copyFileSync(path.join(root,from),path.join(root,to));
const sourceFiles=['scripts/blender/camera_rig.py','scripts/blender/artkit.py','scripts/blender/render.py','engine/lib/sculptures.mjs','fframes/job.mjs','fframes/native/src/media.rs',...['inspection-orbit','parallax-truck'].flatMap(n=>['py','json'].map(e=>`library/sculptures/${n}.${e}`))];
write('evidence/implementation.json',{version:1,inputSha256:binding.inputSha256,sourceFiles:sourceFiles.map(p=>({path:p,sha256:hash(path.join(repo,p))}))});
write('evidence/summary.json',{status:'prototype',continuousPlayback:'unverified',variants,tests:{pass:207,fail:0,skipped:0},source:{variants:4,bakedFrames:772,independentModelAssertions:model.assertions,version1ExactSamples:model.version1ExactSampleComparisons},encoded:{framesDecodedForHolds:holds.reduce((s,r)=>s+r.frames,0),holdComparisons:holds.reduce((s,r)=>s+r.holdFramesChecked,0),maxHoldDifference:Math.max(...holds.map(r=>r.maxHoldDifference)),maxJoinDifference:Math.max(...holds.map(r=>r.boundaryDifference)),registrationSamples:registration.reduce((s,r)=>s+r.samples.length,0),maxRegistrationMeanRgb:Math.max(...registration.map(r=>r.maximumMeanAbsoluteRgb))},limits:['Original qualitative geometry and camera timing encode no measured quantities','Portrait truck is a separate illustrative arrangement, not dimensional equivalence','Bounded geometry and sampled encoded frames do not prove arbitrary occlusion, collision or optics','Continuous subjective playback, master acceptance, square and 4:5 remain open']});
const cards=runs.map(r=>`<article><h2>${r.name.replaceAll('-',' ')}</h2><video controls playsinline preload="none" src="evidence/${r.name}/video.mp4"></video><p><a href="specimens/${r.name}/storyboard.json">Editable native source</a> · <a href="evidence/${r.name}/phone.png">Phone sheet</a></p></article>`).join('\n');
fs.writeFileSync(path.join(root,'preview.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bounded camera travel</title><style>body{margin:0;background:#fafafa;color:#24272c;font:17px/1.5 system-ui}main{max-width:1200px;margin:auto;padding:40px}h1{font-size:42px}h2{font-size:19px}a{color:#344f9c}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:30px}article{padding:20px;border:1px solid #ddd}video{width:100%;height:430px;object-fit:contain;background:#eee}</style><main><h1>Bounded camera travel</h1><p>One orbit and one truck. Four illustrative subjects with separately composed landscape and portrait variants. <strong>Prototype:</strong> bounded geometry and sampled frame review pass; continuous playback acceptance remains open.</p><p><a href="README.md">Use and limits</a> · <a href="REVIEW.md">Independent review</a> · <a href="kit.json">File identities</a></p><div class="grid">${cards}</div></main><script>document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(o=>{if(o!==v)o.pause()})))</script></html>\n`);
function walk(dir,rel=''){return fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(e=>{if(['build','__pycache__','kit.json'].includes(e.name)||e.name.endsWith('.log'))return[];const f=path.join(dir,e.name),p=path.posix.join(rel,e.name);return e.isDirectory()?walk(f,p):[{path:p,bytes:fs.statSync(f).size,sha256:hash(f)}];});}
write('kit.json',{schemaVersion:1,id:'camera-travel-studies',version:'0.1.0',kind:'story-kit',title:'Bounded camera travel',status:'prototype',inventoryIds:['T04','M07'],purpose:'Inspect another view with fixed-geometry orbit and truck moves while keeping native qualifications clear.',tags:{purpose:['inspect','change-view','explain-occlusion'],appearance:['paper','ceramic','graphite','blue','amber'],movement:['bounded-orbit','camera-truck','parallax','reading-hold'],format:['landscape','vertical'],subject:['system-inspection','methods-review','sightline','reporting']},includes:{source:'inputs.json',bindings:'bindings.json',composition:'build.mjs',preview:'preview.html',media:mediaNames.map(n=>`media/${n}`),specimens:runs.map(r=>`specimens/${r.name}/storyboard.json`)},requires:{replay:['ClearFrame native compositor','bundled fonts'],preparation:['Node.js','FFmpeg','Python 3','Blender for source regeneration']},editable:{native:['copy','phase labels','typography','held duration'],procedural:['scene geometry','camera','materials','source timing'],fixedClip:['Prepared pixels; regenerate and review after procedural changes']},evidence:{summary:'evidence/summary.json',review:'REVIEW.md',holds:'evidence/encoded-holds.json',registration:'evidence/registration.json',implementation:'evidence/implementation.json',continuousPlayback:'unverified'},provenance:{references:'SOURCES.md',inputSha256:binding.inputSha256,modelVersion:2},license:'MIT for original files; bundled fonts retain OFL notices.',files:walk(root)});
console.log(JSON.stringify({variants:runs.length,files:read('kit.json').files.length,bytes:read('kit.json').files.reduce((s,f)=>s+f.bytes,0)}));
