// Package current source-bound prototypes after native and independent review.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(root,'../../..'),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p))),write=(p,d)=>fs.writeFileSync(path.join(root,p),JSON.stringify(d,null,2)+'\n');
const audit=read('audit.json'),runs=read('build/verification.json').sort((a,b)=>a.name.localeCompare(b.name)),checks=read('build/encoded-checks.json'),reviews=read('evidence/independent-review/artifact-checks.json');
for(const list of [runs,checks,reviews])if(list.length!==4||new Set(list.map(r=>r.name??r.project)).size!==4)throw Error('Four unique final variants required');
if(audit.inputSha256!==hash(path.join(root,'inputs.json')))throw Error('Inputs changed');
const tests=fs.readFileSync(path.join(root,'build/node-tests.txt'),'utf8');if(!tests.includes('pass 217')||!tests.includes('fail 0')||!tests.includes('skipped 0'))throw Error('Full regression evidence missing');
const critique=read('evidence/critique.json'),rationale=read('evidence/critique-resolution.json');
if(rationale.status!=='retained-for-prototype'||rationale.critiqueSha256!==hash(path.join(root,'evidence/critique.json'))||rationale.inputSha256!==audit.inputSha256)throw Error('Critique rationale stale');
for(const r of critique){const warnings=r.findings.filter(f=>f.level==='warn');if(warnings.length!==1||warnings[0].where!=='trays'||!/^1(?:18|28) words on screen/.test(warnings[0].message))throw Error('Unreviewed critique warning');}
const review=fs.readFileSync(path.join(root,'REVIEW.md'),'utf8');if(!review.includes(audit.inputSha256))throw Error('Review needs input binding');
const model=read('evidence/independent-review/contract-check.json');if(!model.passed||model.assertions<481271||model.negativeCases<70||model.sweptLegPairs<5376)throw Error('Independent model evidence missing');
for(const [f,h]of Object.entries(model.bindings))if(hash(path.join(repo,f))!==h)throw Error('Independent model evidence stale');
for(const [f,h]of Object.entries(read('evidence/independent-review/source-bindings.json')))if(hash(path.join(repo,f))!==h)throw Error('Independent source binding stale: '+f);
const variants=[];
for(const r of runs){
 const specimen=audit.results.find(a=>a.name===r.name),cut=specimen.stages[0].duration,duration=cut+24;
 const dir=path.join(root,'evidence',r.name),video=path.join(dir,'video.mp4'),sb=path.join(root,'specimens',r.name,'storyboard.json'),receipt=JSON.parse(fs.readFileSync(video+'.json')),job=JSON.parse(fs.readFileSync(path.join(dir,'native-job.json'))),probe=checks.find(p=>p.project===r.name),reviewed=reviews.find(p=>p.name===r.name);
 if(r.check.errors.length||r.check.warnings.length||r.qa.pops||!r.seek.equal)throw Error('Native diagnostic remains');
 if(receipt.hashes['storyboard.json']!==hash(sb)||probe.videoSha256!==hash(video)||probe.storyboardSha256!==hash(sb)||probe.checkerSha256!==hash(path.join(root,'check-encoded.py'))||probe.failures)throw Error('Encoded binding stale');
 if(probe.inputSha256!==audit.inputSha256||probe.nativeJobSha256!==hash(path.join(dir,'native-job.json'))||reviewed.nativeJobSha256!==probe.nativeJobSha256||reviewed.duration!==duration||reviewed.encodedReportSha256!==hash(path.join(root,'build/encoded-checks.json')))throw Error('Artifact binding stale');
 if(!reviewed.inspected||reviewed.captures<(cut===22?14:22)||reviewed.videoSha256!==hash(video)||reviewed.storyboardSha256!==hash(sb))throw Error('Independent visual review incomplete');
 if(job.frames!==duration*30||job.fps!==30||job.beats.map(b=>b.frames).join(',')!==`${cut*30},720`)throw Error('Hold timing changed');
 variants.push({name:r.name,pipelineId:r.pipelineId,videoSha256:hash(video),storyboardSha256:hash(sb),check:r.check,qa:r.qa,seekEqual:true});
}
for(const [from,to]of [['build/node-tests.txt','evidence/node-tests.txt'],['build/focused-checks.txt','evidence/focused-checks.txt'],['build/encoded-checks.json','evidence/encoded-checks.json']])fs.copyFileSync(path.join(root,from),path.join(root,to));
write('evidence/implementation.json',{version:1,inputSha256:audit.inputSha256,sourceFiles:['fframes/allocation-data.mjs','fframes/allocations.mjs','fframes/plot-data.mjs','fframes/job.mjs','fframes/native/src/canvas.rs'].map(p=>({path:p,sha256:hash(path.join(repo,p))}))});
const totals=Object.fromEntries(['nativeMappingChecks','arithmeticChecks','sampledFrames','allTrayFrames','componentCountChecks','tokenPoseChecks','tokenCoreChecks','outsideBoundsChecks','barChecks','failures'].map(k=>[k,checks.reduce((s,r)=>s+r[k],0)]));
write('evidence/summary.json',{status:'prototype',continuousPlayback:'unverified',variants,tests:{pass:217,fail:0,skipped:0},encoded:totals,retainedCritiqueWarnings:4,critiqueRationale:'evidence/critique-resolution.json',limits:['Fictional fixed-pool plans; no inflow, spending, loss, return or optimization model','Equal tiles encode equal declared amounts, not equal risk, productivity or benefit','Whole tokens only; native geometry is exact while compressed pixel areas are approximate','One reading-density warning per clip retained with explicit source and sampled-picture rationale','Crowded data or new copy requires fresh layout review','Bounded encoded probes and phone-frame review, not continuous playback or final master acceptance','Square and 4:5 unreviewed']});
const cards=runs.map(r=>`<article><h2>${r.name.replaceAll('-',' ')}</h2><video controls playsinline preload="none" src="evidence/${r.name}/video.mp4"></video><p><a href="specimens/${r.name}/storyboard.json">Editable source</a> · <a href="evidence/${r.name}/phone.png">Phone sheet</a></p></article>`).join('\n');
fs.writeFileSync(path.join(root,'preview.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Allocation trays</title><style>body{margin:0;background:#fafafa;color:#24272c;font:17px/1.5 system-ui}main{max-width:1200px;margin:auto;padding:40px}h1{font-size:42px}h2{font-size:19px}a{color:#344f9c}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:30px}article{padding:20px;border:1px solid #ddd}video{width:100%;height:430px;object-fit:contain;background:#eee}</style><main><h1>Allocation trays</h1><p>Fixed-value tiles move between compartments without changing the total; exact paired bars show the completed plan. Two fictional cases in landscape and vertical. <strong>Prototype:</strong> sampled geometry and frame review pass; continuous playback acceptance remains open.</p><p><a href="README.md">Use and limits</a> · <a href="REVIEW.md">Independent review</a> · <a href="kit.json">File identities</a></p><div class="grid">${cards}</div></main><script>document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(o=>{if(o!==v)o.pause()})))</script></html>\n`);
function walk(dir,rel=''){return fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(e=>{if(['build','__pycache__','kit.json'].includes(e.name))return[];const f=path.join(dir,e.name),p=path.posix.join(rel,e.name);return e.isDirectory()?walk(f,p):[{path:p,bytes:fs.statSync(f).size,sha256:hash(f)}];});}
write('kit.json',{schemaVersion:1,id:'allocation-studies',version:'0.1.0',kind:'story-kit',title:'Allocation trays',status:'prototype',inventoryIds:['I04'],purpose:'Show explicit fixed-quantum transfers with parked-plus-transit conservation, then compare exact before/after allocations.',tags:{purpose:['reallocate','reconcile','compare'],appearance:['paper','native-chart','equal-tiles'],movement:['token-transfer','quantitative-cut','reading-hold'],format:['landscape','vertical'],subject:['budgets','work-hours','fixed-pool']},includes:{source:'inputs.json',calculations:'audit.json',composition:'build.mjs',preview:'preview.html',specimens:runs.map(r=>`specimens/${r.name}/storyboard.json`)},requires:{replay:['ClearFrame native compositor','bundled fonts'],preparation:['Node.js','FFmpeg','Python 3 with NumPy']},editable:{native:['bucket labels','integer counts','fixed quantum','explicit transfers','copy','timing','layout'],fixedClip:[]},evidence:{summary:'evidence/summary.json',review:'REVIEW.md',encoded:'evidence/encoded-checks.json',implementation:'evidence/implementation.json',continuousPlayback:'unverified'},provenance:{references:'SOURCES.md',inputSha256:audit.inputSha256,modelVersion:1},license:'MIT for original files; bundled fonts retain OFL notices.',files:walk(root)});
console.log(JSON.stringify({variants:4,files:read('kit.json').files.length,encoded:totals}));
