const asOf='2026-10-02';
const periods=(n,returnRate,extra={})=>Array.from({length:n},(_,i)=>({label:`Year ${i+1}`,returnRate,...extra}));
const item=(id,recipe,title,source,inputs)=>({id,recipe,title,asOf,source,inputs});
export const cases=[
  item('steady-additions','R01','Two contributions build one account','Illustrative USD, rounded. Year-end additions; 6% assumed return, not a forecast.',
    {periodUnit:'Years',capacity:100000,inspectPeriod:4,account:{openingBalance:10000,cashflowTiming:'end',periods:periods(6,.06,{employee:6000,employer:3000})}}),
  item('losses-with-additions','R01','Adding money does not prevent losses','Illustrative USD, rounded. Year-end additions and supplied returns; no forecast.',
    {periodUnit:'Years',capacity:50000,inspectPeriod:1,account:{openingBalance:30000,cashflowTiming:'end',periods:[-.1,-.2,.1,.06,.04,.03].map((returnRate,i)=>({label:`Year ${i+1}`,returnRate,employee:3000,employer:1000}))}}),
  item('single-match','R02','A match applies only to eligible contributions','Illustrative USD/year, rounded. 50% match through 6% of pay; no true-up assumed.',
    {domain:3000,match:{compensation:60000,employeeContribution:3600,tiers:[{through:.06,rate:.5}]}}),
  item('tiered-match','R02','Each match band has its own rate','Illustrative USD/year, rounded. Supplied marginal tiers; no true-up assumed.',
    {domain:4000,match:{compensation:80000,employeeContribution:6400,tiers:[{through:.03,rate:1},{through:.05,rate:.5}]}}),
  item('graded-ownership','R03','Ownership changes; the total does not','Illustrative USD, rounded. Supplied service schedule; ownership is not withdrawal eligibility.',
    {vesting:{employeeBalance:20000,employerBalance:10000,creditedService:3,schedule:[{service:0,fraction:0},{service:1,fraction:.2},{service:2,fraction:.4},{service:3,fraction:.6},{service:4,fraction:.8},{service:5,fraction:1}]}}),
  item('cliff-ownership','R03','A cliff changes ownership at one threshold','Illustrative USD, rounded. Supplied cliff schedule; ownership is not withdrawal eligibility.',
    {vesting:{employeeBalance:12000,employerBalance:6000,creditedService:2,schedule:[{service:0,fraction:0},{service:3,fraction:1}]}}),
  item('fees-on-reserve','R04','Small rates compound into a balance gap','Illustrative USD, rounded. 5% annual return; no cashflows. Fees after return; no forecast.',
    {periodUnit:'Years',gapDomain:[0,20000],comparison:{baselineFeeRate:.001,comparisonFeeRate:.01,account:{openingBalance:100000,cashflowTiming:'end',periods:periods(8,.05)}}}),
  item('fees-with-loss','R04','The same return path, different fees','Illustrative USD. Returns −15/8/5/10/6/4% yearly; +$6k year-end. Fees after return; no forecast.',
    {periodUnit:'Years',gapDomain:[0,15000],comparison:{baselineFeeRate:.002,comparisonFeeRate:.018,account:{openingBalance:50000,cashflowTiming:'end',periods:[-.15,.08,.05,.1,.06,.04].map((returnRate,i)=>({label:`Year ${i+1}`,returnRate,employee:6000}))}}}),
  item('depleted-account','R05','A request can outlast the account','Illustrative USD, rounded. End-period withdrawals, zero returns/fees; no adequacy claim.',
    {periodUnit:'Years',capacity:30000,inspectPeriod:2,account:{openingBalance:30000,cashflowTiming:'end',periods:periods(3,0,{withdrawal:12000})}}),
  item('funded-account','R05','Funded withdrawals still change the balance','Illustrative USD, rounded. End-year $5k requests, 4% assumed return; no forecast.',
    {periodUnit:'Years',capacity:100000,inspectPeriod:4,account:{openingBalance:100000,cashflowTiming:'end',periods:periods(5,.04,{withdrawal:5000})}}),
  item('adjusted-benefit','R06','A benefit is a formula, not an account','Illustrative salary × service formula. USD, rounded; supplied 90% adjustment.',
    {benefit:{annualCompensation:80000,creditedYears:30,annualAccrualRate:.015,adjustmentFactor:.9}}),
  item('unadjusted-benefit','R06','Each factor has a different unit','Illustrative salary × service formula. USD, rounded; supplied 100% adjustment.',
    {benefit:{annualCompensation:70000,creditedYears:20,annualAccrualRate:.02,adjustmentFactor:1}}),
  item('fixed-quotes','R07','Amounts come with different conditions','Fictional USD quotes. Lifetimes unknown; no value equivalence or ranking.',
    {quotes:[{label:'Lump sum',amount:350000,basis:'one-time',conditions:'No further payments in this quoted offer.'},
      {label:'Single life',amount:2300,basis:'per month',conditions:'Until participant death. No survivor payment; no COLA.'},
      {label:'Joint survivor',amount:2000,basis:'per month',conditions:'Then $1,000/month to survivor. No COLA; lifetimes unknown.'}]}),
  item('conditional-quotes','R07','Read the conditions beside the amount','Fictional USD quotes. Terms supplied; no actuarial valuation or ranking.',
    {quotes:[{label:'Lump sum',amount:280000,basis:'one-time',conditions:'No further payments in this quoted offer.'},
      {label:'Life + guarantee',amount:1750,basis:'per month',conditions:'10-year payment guarantee, then participant life. No COLA.'},
      {label:'Survivor + COLA',amount:1500,basis:'per month',conditions:'75% to survivor; assumed 2% yearly COLA. Lifetimes unknown.'}]}),
  item('rising-prices','R08','A fixed payment buys less as prices rise','Illustrative USD/month. Y0 prices are the real-value base; no COLA or forecast.',
    {periodUnit:'Years from Y0',basePeriod:'Y0',baseIndex:100,amounts:[3000,3000,3000,3000,3000],priceIndices:[100,105,110,120,125]}),
  item('falling-prices','R08','Purchasing power can also rise','Illustrative USD/month. Y0 prices are the real-value base; no COLA or forecast.',
    {periodUnit:'Years from Y0',basePeriod:'Y0',baseIndex:100,amounts:[2500,2500,2500,2500,2500],priceIndices:[100,98,95,96,94]}),
  item('return-order','R09','Withdrawals make the order matter','Illustrative USD, rounded. $15k end-year requests; same return set, no forecast.',
    {openingBalance:100000,capacity:120000,cashflowTiming:'end',withdrawals:[15000,15000,15000,15000],orderA:[-.25,.15,.1,.08],orderB:[.08,.1,.15,-.25]}),
  item('return-order-depletion','R09','Depletion does not erase the shortfall','Illustrative USD, rounded. $20k end-year requests; same return set, no forecast.',
    {openingBalance:60000,capacity:80000,cashflowTiming:'end',withdrawals:[20000,20000,20000,20000],orderA:[-.25,.15,.1,.08],orderB:[.08,.1,.15,-.25]})
];
