// Package current source-bound clips; no promotion to accepted artwork.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(root,'../../..');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),hash=f=>sha(fs.readFileSync(f)),read=f=>JSON.parse(fs.readFileSync(path.join(root,f))),write=(f,v)=>fs.writeFileSync(path.join(root,f),JSON.stringify(v,null,2)+'\n');
const runs=read('build/verification.json').sort((a,b)=>a.name.localeCompare(b.name)),checks=read('build/encoded-checks.json'),audit=read('audit.json');
if(runs.length!==12||new Set(runs.map(r=>r.name)).size!==12||checks.length!==12||new Set(checks.map(r=>r.project)).size!==12)throw Error('Need twelve unique current variants and encoded checks');
if(audit.inputSha256!==hash(path.join(root,'inputs.json')))throw Error('Stale calculation inputs');
if(!fs.existsSync(path.join(root,'REVIEW.md')))throw Error('Independent review required');
const critique=fs.readFileSync(path.join(root,'evidence/critique.txt'),'utf8');if(critique.includes('words on screen'))throw Error('Reading-rate warnings remain');
const tests=fs.readFileSync(path.join(root,'build/node-tests.txt'),'utf8');if(!tests.includes('pass 178')||!tests.includes('fail 0')||!tests.includes('skipped 0'))throw Error('Full regression evidence missing');
const arithmetic=read('evidence/independent-review/arithmetic-review.json');
if(arithmetic.sourceSha256!==hash(path.join(repo,'engine/lib/time-series.mjs'))||!fs.readFileSync(path.join(root,'REVIEW.md'),'utf8').includes(audit.inputSha256))throw Error('Stale independent math/input review');
const reviewed=read('evidence/independent-review/artifact-checks.json');
if(reviewed.length!==12||new Set(reviewed.map(r=>r.name)).size!==12)throw Error('Need twelve independent reviewed variants');
const summary=[];
for(const r of runs){
 if(r.check.errors.length||r.check.warnings.length||r.qa.pops||!r.seek.equal)throw Error(`Unresolved diagnostics: ${r.name}`);
 const out=path.join(root,'evidence',r.name),video=path.join(out,'video.mp4'),receipt=JSON.parse(fs.readFileSync(video+'.json')),p=path.join(root,'specimens',r.name,'storyboard.json'),probe=checks.find(c=>c.project===r.name);
 if(receipt.hashes['storyboard.json']!==hash(p)||!probe||probe.failures||probe.videoSha256!==hash(video)||probe.storyboardSha256!==hash(p))throw Error(`Stale encoded source binding: ${r.name}`);
 const job=JSON.parse(fs.readFileSync(path.join(out,'native-job.json')));if(job.frames/job.fps!==40||job.beats.some(b=>b.frames/job.fps!==20))throw Error(`Reading hold mismatch: ${r.name}`);
 const review=reviewed.find(v=>v.name===r.name);if(!review||review.videoSha256!==hash(video)||review.storyboardSha256!==hash(p)||review.captures!==7||!review.encodedReportHashMatches||review.nativeErrors||review.nativeWarnings||review.qaPops||!review.shuffledSeekEqual)throw Error(`Stale independent review: ${r.name}`);
 summary.push({name:r.name,pipelineId:r.pipelineId,videoSha256:hash(video),storyboardSha256:hash(p),check:r.check,qa:r.qa,seekEqual:r.seek.equal});
}
fs.copyFileSync(path.join(root,'build/node-tests.txt'),path.join(root,'evidence/source-checks.txt'));
fs.copyFileSync(path.join(root,'build/encoded-checks.json'),path.join(root,'evidence/encoded-checks.json'));
fs.copyFileSync(path.join(root,'build/focused-checks.txt'),path.join(root,'evidence/focused-checks.txt'));
const sourceFiles=['engine/lib/time-series.mjs','fframes/plot-data.mjs','fframes/plots.mjs','fframes/catalog.mjs','fframes/validators.mjs','fframes/job.mjs'];
const bindings=sourceFiles.map(p=>({path:p,sha256:hash(path.join(repo,p))}));
write('evidence/implementation.json',{modelVersion:1,inputSha256:audit.inputSha256,sourceFiles:bindings});
write('evidence/summary.json',{status:'prototype',continuousPlayback:'unverified',variants:summary,tests:{pass:178,fail:0,skipped:0},encoded:{sampledFrames:checks.reduce((n,c)=>n+c.sampledFrames,0),nativeMappingChecks:checks.reduce((n,c)=>n+c.nativeMappingChecks,0),pointChecks:checks.reduce((n,c)=>n+c.pointChecks,0),frontChecks:checks.reduce((n,c)=>n+c.frontChecks,0),missingColumnChecks:checks.reduce((n,c)=>n+c.missingColumnChecks,0),failures:0},limitations:['Fictional records, no forecasts or historical financial evidence','Observed peaks do not establish unseen highs/lows','Rolling SD is unannualized variation of monthly percent changes, not risk-adjusted performance','Bounded encoded probes and phone-frame review; no subjective continuous playback or master acceptance','Square and 4:5 are unreviewed']});
const cards=runs.map(r=>`<article><h2>${r.name.replaceAll('-',' ')}</h2><video controls playsinline preload="none" src="evidence/${r.name}/video.mp4"></video><p><a href="specimens/${r.name}/storyboard.json">Editable native source</a> · <a href="evidence/${r.name}/phone.png">Phone sheet</a></p></article>`).join('\n');
fs.writeFileSync(path.join(root,'preview.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Time-series studies</title><style>body{margin:0;background:#f6f4ee;color:#252832;font:17px/1.5 system-ui}main{max-width:1200px;padding:40px;margin:auto}h1{font-size:42px}h2{font-size:19px}a{color:#344f9c}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:30px}article{padding:20px;border:1px solid #d8d4ce}video{width:100%;height:430px;object-fit:contain;background:#eeede7}p{max-width:850px}</style><main><h1>Time-series studies</h1><p>Price basis, discrete growth and observed drawdown. Six original fictional cases, each composed for landscape and vertical. <strong>Prototype:</strong> continuous subjective playback and final master acceptance remain unverified.</p><p><a href="README.md">Use and limits</a> · <a href="SOURCES.md">Sources and assumptions</a> · <a href="REVIEW.md">Independent review</a> · <a href="kit.json">Hashes</a></p><div class="grid">${cards}</div></main><script>document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(o=>{if(o!==v)o.pause()})))</script></html>\n`);
function walk(dir,rel=''){return fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name)).flatMap(e=>{if(['build','__pycache__','kit.json'].includes(e.name))return[];const f=path.join(dir,e.name),p=path.posix.join(rel,e.name);return e.isDirectory()?walk(f,p):[{path:p,bytes:fs.statSync(f).size,sha256:hash(f)}];});}
write('kit.json',{schemaVersion:1,id:'time-series-studies',version:'0.1.0',kind:'story-kit',title:'Time-series studies',status:'prototype',inventoryIds:['C09','C10','C11','T02'],purpose:'Explain matched-price deflation, discrete growth and observed drawdown with complete-window volatility.',tags:{purpose:['compare','transform','observe-risk'],appearance:['paper','blue','orange'],movement:['shared-clock-reveal','reading-hold'],format:['landscape','vertical'],subject:['pay','budgets','output','index-paths']},includes:{source:'inputs.json',calculations:'audit.json',composition:'source/panels.mjs',preview:'preview.html',specimens:runs.map(r=>`specimens/${r.name}/storyboard.json`)},requires:{replay:['ClearFrame native compositor','paper palette','bundled fonts'],preparation:['Node.js','FFmpeg','Python 3']},editable:{native:['values','dates','units','domains','labels','palette','timing'],fixedClip:['Retained MP4 pixels; regenerate and review after source edits']},evidence:{summary:'evidence/summary.json',review:'REVIEW.md',encoded:'evidence/encoded-checks.json',implementation:'evidence/implementation.json',continuousPlayback:'unverified'},provenance:{references:'SOURCES.md',inputSha256:audit.inputSha256,modelVersion:1},license:'MIT for original files; bundled fonts retain OFL notices.',files:walk(root)});
console.log(JSON.stringify({variants:12,files:read('kit.json').files.length,bytes:read('kit.json').files.reduce((n,f)=>n+f.bytes,0)}));
