#!/usr/bin/env python3
"""Compile the pinned MIT Tabler subset into typed, bounded native SVG paths.

Run from any directory. No network, dependencies, arbitrary SVG, or author paths.
"""
import hashlib
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

NATIVE = Path(__file__).resolve().parents[1]
ASSETS = NATIVE.parents[1] / "film/assets/icons/tabler"
MANIFEST = json.loads((ASSETS / "manifest.json").read_text())
REVISION = "74929e50416e2b7c0abb8368cdc74bdcb2560ab6"
assert MANIFEST["repository"] == "https://github.com/tabler/tabler-icons"
assert MANIFEST["revision"] == REVISION and MANIFEST["license"] == "MIT"
ROOT_ATTRIBUTES = {
    "width": "24", "height": "24", "viewBox": "0 0 24 24", "fill": "none",
    "stroke": "currentColor", "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round",
}
icons = {}
for entry in MANIFEST["files"]:
    filename = entry["file"]
    assert Path(filename).name == filename
    data = (ASSETS / filename).read_bytes()
    assert hashlib.sha256(data).hexdigest() == entry["sha256"], filename
    if filename == "LICENSE":
        assert data.startswith(b"MIT License")
        continue
    assert filename.endswith(".svg")
    root = ET.fromstring(data)
    assert root.tag == "{http://www.w3.org/2000/svg}svg" and root.attrib == ROOT_ATTRIBUTES, filename
    paths = []
    for element in root:
        assert element.tag == "{http://www.w3.org/2000/svg}path", filename
        if element.attrib.get("stroke") == "none" and element.attrib.get("fill") == "none":
            assert set(element.attrib) == {"d", "stroke", "fill"}
            continue  # Invisible upstream bounds path, if present.
        assert set(element.attrib) == {"d"}, filename
        path = element.attrib["d"]
        assert len(path) < 4096 and re.fullmatch(r"[MmLlHhVvCcSsQqTtAaZzEe0-9.,+\s-]+", path), filename
        paths.append(path)
    assert 1 <= len(paths) <= 30
    icons[filename.removesuffix(".svg")] = paths
assert len(icons) == sum(entry["file"].endswith(".svg") for entry in MANIFEST["files"])

header = """// SPDX-License-Identifier: MIT
// Tabler icon geometry: Copyright (c) 2020-2026 Paweł Kuna.
// Generated by scene/native/tools/generate-icons.py. Do not edit path data by hand.
// Source: github.com/tabler/tabler-icons @ """ + REVISION + """
// Full license and per-file source/SHA256: film/assets/icons/tabler/{LICENSE,manifest.json}.
use crate::draw::{self, Node};

pub fn paths(name: &str) -> Option<&'static [&'static str]> {
    match name {
"""
output = [header]
for name, paths in sorted(icons.items()):
    output.append(f'        "{name}" => Some(&[\n')
    for path in paths:
        output.append(f'            "{path}",\n')
    output.append("        ]),\n")
output.append("""        _ => None,
    }
}

pub fn supported(name: &str) -> bool { paths(name).is_some() }

/// Only an enumerated, locally pinned icon is allowed; props never supply SVG.
pub(crate) fn render(name: &str, x: f32, y: f32, size: f32, color: &str) -> Node {
    let geometry = paths(name).unwrap_or_else(|| panic!("unsupported native icon {name}"));
    let shapes: Vec<Node> = geometry.iter().map(|d| draw::path(d).stroke(color, 2.0).round().node()).collect();
    draw::group(shapes).transform(skia_safe::Matrix::scale_translate((size / 24.0, size / 24.0), (x, y)))
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn only_named_trusted_icons_are_accepted() {
        assert!(supported("leaf"));
        assert!(supported("book-open"));
        assert!(!supported("../leaf.svg"));
        assert!(!supported("<svg><script>bad</script></svg>"));
    }
    #[test]
    fn pinned_geometry_draws_in_the_authored_colour() {
        let icon = render("leaf", 20.0, 40.0, 72.0, "#123456");
        let b = icon.bounds().expect("icon geometry");
        assert!(b.left >= 20.0 && b.top >= 40.0 && b.right <= 92.0 && b.bottom <= 112.0, "{b:?}");
        let crate::draw::Node::Group(g) = &icon else { panic!("a group") };
        let crate::draw::Node::Shape(s) = &g.children[0] else { panic!("a shape") };
        assert!(s.fill.is_none());
        assert!(matches!(s.stroke.as_ref().map(|s| &s.ink), Some(crate::draw::Ink::Color(c)) if (c.r - 0x12 as f32 / 255.0).abs() < 1e-3));
    }
}
""")
(NATIVE / "src/icons.rs").write_text("".join(output))
print(f"Verified and generated {len(icons)} MIT Tabler icons at revision {REVISION}.")
