// Independent observed-sample membership, density and native geometry review.
import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {distribution} from '../../../../../fframes/distribution-data.mjs';
import {distributionScene,thresholdLabel} from '../../../../../fframes/distributions.mjs';
let assertions=0,modelCases=0;const eq=(a,b)=>{assert.deepEqual(a,b);assertions++;},ok=v=>{assert(v);assertions++;},near=(a,b,tol=1e-10)=>{assert(Math.abs(a-b)<=tol,`${a} != ${b}`);assertions++;},reject=f=>{assert.throws(f);assertions++;};
const fixture=()=>({title:'Independent finite sample',source:'Original fictional observations.',asOf:'2026-09-30',unit:'units',observations:[-2,-1,0,1,2,null],edges:[-2,0,2],mode:'count',threshold:{value:0,relation:'gte'},y:{max:240,ticks:[0,120,240],decimals:0}});
const qualifies=(v,t)=>t.relation==='gte'?!(v<t.value):t.relation==='gt'?t.value<v:t.relation==='lte'?!(t.value<v):v<t.value;
function review(f){const before=structuredClone(f),m=distribution(f),used=f.observations.filter(v=>v!==null),n=used.length;modelCases++;eq(f,before);eq(m.n,n);eq(m.missing,f.observations.length-n);eq(m.edges,f.edges);eq(m.observations.map(v=>v.value),f.observations);eq(m.y,{...f.y,decimals:f.y.decimals??0});
 // Reference bin index is the number of passed internal boundaries. It does
 // not reuse the implementation's left/right interval search.
 const assignments=f.observations.map(v=>v===null?null:f.edges.slice(1,-1).filter(edge=>v>=edge).length);
 eq(m.observations.map(v=>v.bin),assignments);eq(m.observations.map(v=>v.qualifies),f.observations.map(v=>v===null?null:qualifies(v,f.threshold)));eq(m.bins.length,f.edges.length-1);
 for(const [i,b]of m.bins.entries()){const members=assignments.flatMap((bin,j)=>bin===i?[j]:[]);eq(b.members,members);eq(b.count,members.length);eq(b.low,f.edges[i]);eq(b.high,f.edges[i+1]);eq(b.width,f.edges[i+1]-f.edges[i]);eq(b.rightClosed,i===f.edges.length-2);const expectedHeight=f.mode==='count'?members.length:members.length/(n*(f.edges[i+1]-f.edges[i]));near(b.height,expectedHeight,4*Number.EPSILON*Math.max(Math.abs(expectedHeight),1e-300));}
 eq(m.bins.reduce((s,b)=>s+b.count,0),n);if(f.mode==='density')near(m.bins.reduce((s,b)=>s+b.height*b.width,0),1,2e-15);
 const tail=f.observations.flatMap((v,i)=>v!==null&&qualifies(v,f.threshold)?[i]:[]);eq(m.threshold,{...f.threshold,count:tail.length,denominator:n,fraction:tail.length/n,members:tail});eq(m.missingPolicy,'null excluded from observed denominator; counted explicitly');eq(m.edgePolicy,'left-closed right-open; final bin right-closed');return m;}
const pool=[-2,-1,0,1,2,null];
for(let length=1;length<=3;length++)for(let code=0;code<pool.length**length;code++){
 const values=Array.from({length},(_,i)=>pool[Math.floor(code/pool.length**i)%pool.length]);if(values.every(v=>v===null))continue;
 for(const mode of ['count','density'])for(const relation of ['gte','gt','lte','lt'])for(const value of [-2,-1,0,.5,2]){const f=fixture();f.observations=values;f.mode=mode;f.edges=mode==='count'?[-2,0,2]:[-2,-1,2];f.threshold={value,relation};review(f);}
}
for(const observations of [Array.from({length:240},(_,i)=>i%7===0?null:i%5-2),[-2,-2,-2],[-0,0,Number.MIN_VALUE],[-2,2]])review({...fixture(),observations});
for(const [edges,values]of [[[0,1e-9,2e-9],[0,.5e-9,1e-9,2e-9]],[[-1e9,0,1e9],[-1e9,0,1e9]]])for(const mode of ['count','density']){const f=fixture();f.edges=edges;f.observations=values;f.mode=mode;f.threshold.value=0;f.y={max:1e9,ticks:[0,1e9],decimals:0};review(f);}
const modelAssertions=assertions;
for(const edit of [f=>delete f.observations[1],f=>delete f.edges[1],f=>delete f.y.ticks[1],f=>f.observations=[],f=>f.observations=Array(241).fill(0),f=>f.observations=[null,null],f=>f.observations=[NaN],f=>f.observations=[Infinity],f=>f.observations=['1'],f=>f.observations=[3],f=>f.edges=[-2,2],f=>f.edges=Array.from({length:14},(_,i)=>i),f=>f.edges=[-2,0,0,2],f=>f.edges=[-2,1,0,2],f=>f.edges=[-2,0,Infinity],f=>f.edges=[-2,0,1e9+1],f=>f.edges=[0,1e-10,1],f=>f.edges=[-2,-1,2],f=>f.mode='probability',f=>f.threshold.value=3,f=>f.threshold.relation='above',f=>f.threshold.extra=true,f=>f.y.max=1,f=>f.y.max=Infinity,f=>f.y.ticks=[1,240],f=>f.y.ticks=[0,120,120,240],f=>f.y.ticks=[0,.1,240],f=>f.y.decimals=-1,f=>f.y.decimals=10,f=>f.y.extra=true,f=>f.asOf='2026-02-30',f=>f.title='',f=>f.unit=' '.repeat(10),f=>f.source='x'.repeat(161),f=>f.extra=true]){const f=fixture();edit(f);reject(()=>distribution(f));}
const guardAssertions=assertions-modelAssertions;
for(const [width,height]of [[1920,1080],[1080,1920],[640,640],[4096,2160]])for(const mode of ['count','density'])for(const relation of ['gte','gt','lte','lt']){
 const f=fixture();f.observations=[-2,-2,-1,-.5,0,0,1,2,null];f.mode=mode;f.edges=mode==='count'?[-2,0,2]:[-2,-1,2];f.threshold={value:0,relation};f.y=mode==='count'?{max:8,ticks:[0,4,8],decimals:0}:{max:1,ticks:[0,1],decimals:0};
 const a=distributionScene(f,{width,height,id:'hist',reveal:true}),b=distributionScene(f,{width,height,id:'tail',focus:true});eq(a.geometry.bars.map(v=>v.box),b.geometry.bars.map(v=>v.box));eq(a.geometry.points.map(v=>v.point),b.geometry.points.map(v=>v.point));const top=height*(height>width?.31:.32),bottom=height*(height>width?.59:.62),left=width*.19,right=width*.89;
 for(const bar of a.geometry.bars){const [x,y,w,h]=bar.box;near(x,left+(bar.low+2)/4*(right-left));near(w,bar.width/4*(right-left));near(h,bar.height/f.y.max*(bottom-top));near(y+h,bottom);ok(bar.count===0||h>0);const element=a.props.elements.find(e=>e.id===`hist-bar-${bar.index}`);if(bar.count===0)eq(element,undefined);else{eq(element.origin,[x,bottom]);eq(element.keys,[{at:0,scaleY:0,dur:0},{at:.4+bar.index*.16,scaleY:1,dur:.8,ease:'linear'}]);eq(element.fill,'accent');}eq(a.props.elements.find(e=>e.id===`hist-count-${bar.index}`).text,`n=${bar.count}`);near(a.props.elements.find(e=>e.id===`hist-count-${bar.index}`).at,bar.end);eq(b.props.elements.find(e=>e.id===`tail-bar-${bar.index}`)?.fill,element?.fill);const background=b.props.elements.find(e=>e.id===`tail-count-bg-${bar.index}`),label=b.props.elements.find(e=>e.id===`tail-count-${bar.index}`);ok(background.y+background.h<=bar.box[1]+1e-10);ok(b.props.elements.indexOf(background)<b.props.elements.indexOf(label));for(const e of b.props.elements.filter(e=>e.id.startsWith('tail-threshold-')))ok(b.props.elements.indexOf(e)<b.props.elements.indexOf(background));}
 near(b.geometry.threshold.x,left+.5*(right-left));eq(b.geometry.threshold.segments[0],[top,bottom]);eq(b.geometry.threshold.at,.2);eq(b.geometry.threshold.end,1);eq(b.geometry.points.filter(p=>p.selected).map(p=>p.index).sort((a,b)=>a-b),b.model.threshold.members);
 for(const p of b.geometry.points){near(p.point[0],left+(p.value+2)/4*(right-left));const radius=p.selected?p.r*1.3+1.5:p.r;ok(p.point[1]+radius<=height*(height>width?.79:.83)+1e-10);const ring=b.props.elements.find(e=>e.id===`tail-selected-${p.index}`);if(p.selected){eq(ring.fill,'none');eq(ring.stroke,'ink');eq(ring.width,3);near(ring.at,.45);}else eq(ring,undefined);
  for(const q of b.geometry.points)if(q.index>p.index){const other=q.selected?q.r*1.3+1.5:q.r;ok(Math.hypot(p.point[0]-q.point[0],p.point[1]-q.point[1])+1e-10>=radius+other);}
 }
 eq(b.props.elements.find(e=>e.id==='tail-summary').text,`${b.model.threshold.count} of ${b.model.n} observed ${thresholdLabel(f.threshold)} units`);
}
for(const options of [{width:639},{height:4097},{id:'Bad id'},{focus:1},{reveal:'yes'}])reject(()=>distributionScene(fixture(),{width:1080,height:1920,id:'valid',...options}));
reject(()=>distributionScene({...fixture(),y:{max:1e308,ticks:[0,1e308],decimals:0}},{width:1080,height:1920,id:'collapse'}));
reject(()=>distributionScene({...fixture(),observations:Array(240).fill(0)},{width:640,height:640,id:'crowded'}));
reject(()=>distributionScene({...fixture(),mode:'density',edges:[-2,-1.999,2],y:{max:1e6,ticks:[0,1e6],decimals:0}},{width:1080,height:1920,id:'thin'}));
const geometryAssertions=assertions-modelAssertions-guardAssertions;
const kit=JSON.parse(fs.readFileSync(new URL('../../inputs.json',import.meta.url))),audit=JSON.parse(fs.readFileSync(new URL('../../audit.json',import.meta.url)));
for(const r of audit.results){const {id,...f}=kit.cases.find(c=>c.id===r.caseId),m=review(f);eq(r.recipe,'C13');eq(r.stages.length,2);for(const stage of r.stages)eq(stage.model,m);eq(r.stages[0].geometry.bars.map(b=>b.box),r.stages[1].geometry.bars.map(b=>b.box));eq(r.stages[0].geometry.points.map(p=>p.point),r.stages[1].geometry.points.map(p=>p.point));eq(r.stages[1].geometry.points.filter(p=>p.selected).map(p=>p.index).sort((a,b)=>a-b),m.threshold.members);}
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(new URL(p,import.meta.url))).digest('hex');const report={status:'pass',assertions,modelCases,modelAssertions,guardAssertions,geometryAssertions,kitAuditAssertions:assertions-modelAssertions-guardAssertions-geometryAssertions,reference:'Independent boundary-count bin assignment; exact observed threshold comparisons; density count/(observed n times bin width); direct native affine positions and ring-inclusive distances.',formulaSource:'https://www.itl.nist.gov/div898/handbook/eda/section3/eda33e.htm',scope:'Bounded source, math, scene and current fictional kit audit only; no render, browser, continuous playback or full repository suite.',inputSha256:sha('../../inputs.json'),auditSha256:sha('../../audit.json'),sourceHashes:Object.fromEntries(['distribution-data.mjs','distributions.mjs'].map(n=>[n,sha('../../../../../fframes/'+n)]))};fs.writeFileSync(new URL('contract-review.json',import.meta.url),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
