import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {fileURLToPath}from'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),kit=path.resolve(here,'../..'),root=path.resolve(kit,'../../..');
const read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const rows=read(path.join(kit,'evidence/verification.json')),audit=read(path.join(kit,'audit.json')),frames=read(path.join(here,'frames.json')),checks=[];assert.equal(rows.length,4);assert.equal(new Set(rows.map(r=>r.name)).size,4);assert.equal(audit.inputSha256,sha(path.join(kit,'inputs.json')));
for(const r of rows){const dir=path.join(kit,'evidence',r.name),receipt=read(path.join(dir,'video.mp4.json')),job=read(path.join(dir,'native-job.json')),f=frames.find(f=>f.name===r.name),a=audit.results.find(a=>a.name===r.name),story=path.join(kit,'specimens',r.name,'storyboard.json');
 assert.deepEqual(read(path.join(dir,'check.json')),r.check);assert.deepEqual(read(path.join(dir,'qa.json')).summary,r.qa);assert.deepEqual(read(path.join(dir,'seek.json')),r.seek);assert.equal(a.storyboardSha256,sha(story));assert.equal(receipt.hashes['storyboard.json'],sha(story));assert.equal(receipt.outputSha256,sha(path.join(dir,'video.mp4')));assert.equal(receipt.outputSha256,f.videoSha256);assert.equal(f.pipelineId,r.pipelineId);assert.equal(f.visuallyInspected,true);assert.deepEqual(r.check.errors,[]);assert.deepEqual(r.check.warnings,[]);assert.equal(r.qa.pops,0);assert.equal(r.seek.equal,true);const cut=a.stages.find(s=>s.id==='trays').duration,total=cut+24;assert.equal(f.cut,cut);assert.equal(f.duration,total);assert.equal(r.qa.seconds,total);assert.equal(receipt.frames/receipt.fps,total);assert.equal(job.frames/job.fps,total);assert.equal(job.beats.length,2);assert.equal(job.beats[0].frames/job.fps,cut);assert.equal(job.beats[1].frames/job.fps,24);assert.equal(f.frames.length,cut===22?14:22);for(const frame of f.frames)assert.equal(frame.sha256,sha(path.join(kit,frame.path)));
 checks.push({name:r.name,pipelineId:r.pipelineId,storyboardSha256:sha(story),videoSha256:receipt.outputSha256,nativeJobSha256:sha(path.join(dir,'native-job.json')),receiptSha256:sha(path.join(dir,'video.mp4.json')),duration:receipt.frames/receipt.fps,encodeSeconds:receipt.seconds,captures:f.frames.length,inspected:f.visuallyInspected,encodedReportSha256:sha(path.join(kit,'evidence/encoded-checks.json')),errors:0,warnings:0,pops:0,seekEqual:true});}
const encoded=read(path.join(kit,'evidence/encoded-checks.json'));assert.equal(encoded.length,4);for(const row of encoded){const c=checks.find(c=>c.name===row.project);assert.ok(c);assert.equal(row.videoSha256,c.videoSha256);assert.equal(row.storyboardSha256,c.storyboardSha256);assert.equal(row.nativeJobSha256,c.nativeJobSha256);assert.equal(row.inputSha256,sha(path.join(kit,'inputs.json')));assert.equal(row.checkerSha256,sha(path.join(kit,'check-encoded.py')));assert.equal(row.failures,0);}
const rebuild=read(path.join(kit,'evidence/rebuild.json'));assert.equal(rebuild.equal,true);for(const [p,h]of Object.entries(rebuild.files))assert.equal(sha(path.join(root,p)),h);
const contract=read(path.join(here,'contract-check.json'));for(const [p,h]of Object.entries(contract.bindings))assert.equal(sha(path.join(root,p)),h);
const report={status:'pass',encodedReportSha256:sha(path.join(kit,'evidence/encoded-checks.json')),scope:'Current source hashes, authored/audit/encoded artifact identity, duration and final-frame review receipts; parent native outcomes inspected rather than independently rerun',checks};fs.writeFileSync(path.join(here,'artifact-checks.json'),JSON.stringify(checks,null,2)+'\n');console.log(JSON.stringify(report));
